<a href="https://colab.research.google.com/github/Edinaldobjr/aulas_de_python/blob/master/exercicios/edinaldo_aula_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dicionários

Todos os tipos de **dados compostos** (***compounds***) que estudamos em detalhes até agora - strings, listas - são **tipos de sequência**, que usam inteiros como índices para acessar os valores que contêm dentro deles.

Os **dicionários** são outro tipo de composto. Eles são o **tipo de mapeamento** integrado do Python. Eles mapeiam **chaves** (**keys**), que podem ser de qualquer **tipo imutável**, para valores, que podem ser de qualquer tipo (heterogêneos), assim como os elementos de uma lista ou tupla. 


**dicionários: chave -> valor**

In [1]:
tradutor = {}                # atribuição de criação de um dicionário vazio
tradutor["one"] = "um"       # atribuição do par key:value
tradutor["two"] = "dois"
tradutor["three"] = "tres"
print(tradutor)

{'one': 'um', 'two': 'dois', 'three': 'tres'}


Os pares de ***key:valor*** do dicionário são separados por vírgulas. Cada par contém uma ***key*** e um valor separados por dois pontos.

In [2]:
frutas = {"maçãs": 430, "bananas": 312, "laranjas": 525, "peras": 217, "goiabas": 88, "figos": 108, "jambos": 249}
print (frutas)

{'maçãs': 430, 'bananas': 312, 'laranjas': 525, 'peras': 217, 'goiabas': 88, 'figos': 108, 'jambos': 249}


**Dicionários não são ordenados!!!!**

In [3]:
dict = {}
for i in range(200):
    dict[i] = "valor" + str(i)
print (dict)

{0: 'valor0', 1: 'valor1', 2: 'valor2', 3: 'valor3', 4: 'valor4', 5: 'valor5', 6: 'valor6', 7: 'valor7', 8: 'valor8', 9: 'valor9', 10: 'valor10', 11: 'valor11', 12: 'valor12', 13: 'valor13', 14: 'valor14', 15: 'valor15', 16: 'valor16', 17: 'valor17', 18: 'valor18', 19: 'valor19', 20: 'valor20', 21: 'valor21', 22: 'valor22', 23: 'valor23', 24: 'valor24', 25: 'valor25', 26: 'valor26', 27: 'valor27', 28: 'valor28', 29: 'valor29', 30: 'valor30', 31: 'valor31', 32: 'valor32', 33: 'valor33', 34: 'valor34', 35: 'valor35', 36: 'valor36', 37: 'valor37', 38: 'valor38', 39: 'valor39', 40: 'valor40', 41: 'valor41', 42: 'valor42', 43: 'valor43', 44: 'valor44', 45: 'valor45', 46: 'valor46', 47: 'valor47', 48: 'valor48', 49: 'valor49', 50: 'valor50', 51: 'valor51', 52: 'valor52', 53: 'valor53', 54: 'valor54', 55: 'valor55', 56: 'valor56', 57: 'valor57', 58: 'valor58', 59: 'valor59', 60: 'valor60', 61: 'valor61', 62: 'valor62', 63: 'valor63', 64: 'valor64', 65: 'valor65', 66: 'valor66', 67: 'valor67',

In [4]:
print(dict[48])     # dicionário [chave] retorna valor na chave.

valor48


In [5]:
print(tradutor["two"])

dois


Até agora, os tipos de dados que tínhamos visto, eram sequências, como listas e strings. Porém **os dicionários não são sequências, sendo assim não podemos indexá-los**.

## Operações com dicionários

A instrução ***del*** retira um par key:valor de um dicionário. Por exemplo, o dicionário a seguir contém os nomes de várias frutas e o número de cada fruta em estoque:

In [6]:
frutas = {"maçãs": 430, "bananas": 312, "laranjas": 525, "peras": 217, "goiabas": 88, "figos": 108, "jambos": 249}
print(frutas)

{'maçãs': 430, 'bananas': 312, 'laranjas': 525, 'peras': 217, 'goiabas': 88, 'figos': 108, 'jambos': 249}


In [7]:
del frutas["peras"]
print(frutas)

{'maçãs': 430, 'bananas': 312, 'laranjas': 525, 'goiabas': 88, 'figos': 108, 'jambos': 249}


In [8]:
frutas["peras"] = 0
print(frutas)

{'maçãs': 430, 'bananas': 312, 'laranjas': 525, 'goiabas': 88, 'figos': 108, 'jambos': 249, 'peras': 0}


In [9]:
frutas["abacaxi"] = 248
print(frutas)

{'maçãs': 430, 'bananas': 312, 'laranjas': 525, 'goiabas': 88, 'figos': 108, 'jambos': 249, 'peras': 0, 'abacaxi': 248}


In [10]:
len(frutas)  #a função len também funciona com dicionários

8

## Métodos de dicionários

Dicionários têm vários métodos úteis.

Podemos visualizar as ***keys*** de um dado dicionário:

In [11]:
frutas.keys()

dict_keys(['maçãs', 'bananas', 'laranjas', 'goiabas', 'figos', 'jambos', 'peras', 'abacaxi'])

In [12]:
for fruta in frutas.keys():
    print(fruta, ' = ', frutas[fruta])

maçãs  =  430
bananas  =  312
laranjas  =  525
goiabas  =  88
figos  =  108
jambos  =  249
peras  =  0
abacaxi  =  248


In [13]:
print(frutas)

{'maçãs': 430, 'bananas': 312, 'laranjas': 525, 'goiabas': 88, 'figos': 108, 'jambos': 249, 'peras': 0, 'abacaxi': 248}


In [14]:
lista_frutas = list(frutas.keys())
print(lista_frutas)

['maçãs', 'bananas', 'laranjas', 'goiabas', 'figos', 'jambos', 'peras', 'abacaxi']


É tão comum iterar sobre as ***keys*** de um dicionário que podemos omitir a chamada do método de ***keys*** no loop ***for***
   * **iterar sobre um dicionário itera implicitamente sobre suas chaves:**

In [15]:
for fruta in frutas:
    print(fruta, ' = ', frutas[fruta])

maçãs  =  430
bananas  =  312
laranjas  =  525
goiabas  =  88
figos  =  108
jambos  =  249
peras  =  0
abacaxi  =  248


In [16]:
keys_frutas = [fruta for fruta in frutas] # list comprehension
print(keys_frutas)

['maçãs', 'bananas', 'laranjas', 'goiabas', 'figos', 'jambos', 'peras', 'abacaxi']


In [17]:
valores_frutas = [frutas[fruta] for fruta in frutas]
print(valores_frutas)

[430, 312, 525, 88, 108, 249, 0, 248]


O método **values** nos possibilita acessar diretamente os valores do dicionário:

In [18]:
valores = list(frutas.values())
print(valores)

[430, 312, 525, 88, 108, 249, 0, 248]


O método ***items*** retorna uma tupla para cada par (***key:valor***):

In [19]:
list(frutas.items())

[('maçãs', 430),
 ('bananas', 312),
 ('laranjas', 525),
 ('goiabas', 88),
 ('figos', 108),
 ('jambos', 249),
 ('peras', 0),
 ('abacaxi', 248)]

As tuplas podem ser úteis para obter a ***key*** e o valor ao mesmo tempo durante a execução do loop:

In [20]:
for (k,v) in frutas.items():
    print("Encontrei a key",k,"que mapeia para o valor",v)

Encontrei a key maçãs que mapeia para o valor 430
Encontrei a key bananas que mapeia para o valor 312
Encontrei a key laranjas que mapeia para o valor 525
Encontrei a key goiabas que mapeia para o valor 88
Encontrei a key figos que mapeia para o valor 108
Encontrei a key jambos que mapeia para o valor 249
Encontrei a key peras que mapeia para o valor 0
Encontrei a key abacaxi que mapeia para o valor 248


Os operadores ***in*** e ***not in*** podem testar se uma chave está no dicionário:

In [21]:
"bananas" in frutas

True

In [22]:
 "jambos" in frutas

True

Esse método pode ser bastante útil pois ao tentar acessar uma ***key*** não exitente, Python retorna um erro de execução:

In [23]:
frutas["mangas"]

KeyError: ignored

O método ***get*** é também bem útil. Ele retorna o valor da ***key*** especificada e caso a ***key*** não exista, retorna o valor indicado como parâmetro:

In [24]:
matrix = {(0, 3): 1, (2, 1): 2, (4, 3): 3}
matrix.get((4,3))

3

In [25]:
matrix.get((2,2))
print(matrix)

{(0, 3): 1, (2, 1): 2, (4, 3): 3}


In [26]:
matrix.get((2,2), 0)      # se existir imprime o valor de (2,2), caso não imprime 0.

0

## Aliasing e cópia

Como no caso das listas, porque os **dicionários são mutáveis**, precisamos estar cientes do **aliasing**. 

Sempre que duas variáveis se referem ao mesmo objeto, as alterações em uma afetam a outra.

Se quiser modificar um dicionário e manter uma cópia do original, use o método de **cópia**. 

Consideremos um dicionário chamado **opostos**, que contém pares de opostos:

In [27]:
opostos = {"up": "down", "right": "wrong", "yes": "no"}    # criação de um dicionário
alias = opostos                                            # criação de um alias. o dicionário alias e opostos se referem ao mesmo objeto.
copia = opostos.copy()                                     # cópia do dicionario opostos        

* Os dicionários ***alias*** e ***opostos*** se referem ao **mesmo objeto**; 
* O dicionário ***copia*** se refere a uma nova cópia do mesmo dicionário. 
* Se modificarmos o ***alias***, o dicionário ***opostos*** também será alterado:

In [28]:
print(alias)

{'up': 'down', 'right': 'wrong', 'yes': 'no'}


In [29]:
alias["right"] = "left"
print(opostos)

{'up': 'down', 'right': 'left', 'yes': 'no'}


In [30]:
print(copia)

{'up': 'down', 'right': 'wrong', 'yes': 'no'}


In [31]:
copia["goodbye"] = "hello"
print(copia)

{'up': 'down', 'right': 'wrong', 'yes': 'no', 'goodbye': 'hello'}


# Exercícios:



1) Utilizando dicionários e o método ***get***, contrua a seguinte matriz em python e acesse os valores de índices (0,3), (2,1), (4,3) e (2,2).
![matrix](https://github.com/malbouis/Python_intro/blob/master/aulas_2019/pics/matrix_aula12.png?raw=1)

In [48]:
matriz = {(0,0): 0, (0,1): 0, (0,2): 0, (0,3): 1, (0,4): 0, 
          (1,0): 0, (1,1): 0, (1,2): 0, (1,3): 0, (1,4): 0, 
          (2,0): 0, (2,1): 2, (2,2): 0, (2,3): 0, (2,4): 0, 
          (3,0): 0, (3,1): 0, (3,2): 0, (3,3): 0, (3,4): 0, 
          (4,0): 0, (4,1): 0, (4,2): 0, (4,3): 3, (4,4): 0}

print('Posição (0,3):',matriz.get((0,3)))
print('Posição (2,1):',matriz.get((2,1)))
print('Posição (4,3):',matriz.get((4,3)))
print('Posição (2,2):',matriz.get((2,2)))

Posição (0,3): 1
Posição (2,1): 2
Posição (4,3): 3
Posição (2,2): 0


In [47]:
matriz2 = {(i, j): 0 for i in range(5) for j in range(5)}   # Criando a matriz zero 5x5
# Colocando os valores nos indices do exercicio
matriz2[(0,3)] = 1
matriz2[(2,1)] = 2
matriz2[(4,3)] = 3

print('Posição (0,3):',matriz2.get((0,3)))
print('Posição (2,1):',matriz2.get((2,1)))
print('Posição (4,3):',matriz2.get((4,3)))
print('Posição (2,2):',matriz2.get((2,2)))

Posição (0,3): 1
Posição (2,1): 2
Posição (4,3): 3
Posição (2,2): 0


b) Faça o mesmo utilizando o pacote numpy.

In [42]:
import numpy as np

matriznp = np.zeros((5,5))

print(matriznp)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [50]:
diconarionp = np.array([[0, 0, 0, 1, 0], [0,0,0,0,0],[0,2,0,0,0], [0,0,0,0,0], [0,0,0,3,0]])

2) Contagem de Letras. 

a) Utilizando dicionários, escreva uma função que tome como argumento uma palavra (string) e  retorne um dicionário que tem como ***key*** a letra da palavra e como valor o número de vezes que ela aparece na palavra. Tal dicionário é chamado de **tabela de frequência**.
***Dica***: Utilize o método ***get*** dos dicionários.



In [104]:
palavra = 'inconstitucional'.upper().replace(' ','')
dicio = {}
 
for i in range(len(palavra)):
    dicio[palavra[i]] = palavra.count(palavra[i])
 
print(dicio)

{'I': 3, 'N': 3, 'C': 2, 'O': 2, 'S': 1, 'T': 2, 'U': 1, 'A': 1, 'L': 1}


b) Utilizando os métodos sort() (referente a listas) e items() (referente a dicionários), imprima na tela uma lista ordenada alfabeticamente da tabela de frequência obtida no item a).

In [109]:
ordenado = sorted(dicio)
print(ordenado)

for i in ordenado:
  print(f'{i} = {dicio[i]}')

['A', 'C', 'I', 'L', 'N', 'O', 'S', 'T', 'U']
A = 1
C = 2
I = 3
L = 1
N = 3
O = 2
S = 1
T = 2
U = 1


3) Escreva um programa que leia uma string e retorne uma tabela das letras do alfabeto em ordem alfabética que ocorrem na string junto com o número de vezes que cada letra ocorre. Letras maiúsculas devem deve ser ignoradas. Um exemplo de saída do programa quando o usuário digita os dados “ThiS is String with Upper and lower case Letters”, seria o seguinte:

a  2

c  1


d  1


e  5


g  1


h  2


i  4


l  2


n  2


o  1


p  2


r  4


s  5


t  5


u  1


w  2

In [112]:
palavra = input('Qual a palavra desejada? ').lower().replace(' ','')
dicio = {}
 
for i in range(len(palavra)):
    dicio[palavra[i]] = palavra.count(palavra[i])
 
ordenado = sorted(dicio)

for i in ordenado:
  print(f'{i} = {dicio[i]}')

Qual a palavra desejada? ThiS is String with Upper and lower case Letters
a = 2
c = 1
d = 1
e = 5
g = 1
h = 2
i = 4
l = 2
n = 2
o = 1
p = 2
r = 4
s = 5
t = 5
u = 1
w = 2
